### PR TITLE
Update i-nex.spec

### PR DESCRIPTION
**Pull request by alphastar868**
Fixes to remove "Recommends:" directives from SPEC file, which breaks RedHat RPM.

### CODE REVIEW

**Comment by eloaders** [comment]
Image files for the cards must have a transparent background and size 160px / 160px

**Comment by alphastar868** [comment]
Okay, I believe I corrected the issues with the logos now.

I've also included an update that should enable detection of many newer (2014 and later) Skylake, Broadwell and Haswell Intel Core-i7s.

**Comment by eloaders** [comment]
Good thanks. I believe that the details are correct. How do you write data? Kate, gedit?

**Comment by alphastar868** [comment]
Interestingly, I found this to help alot: [JSONedit](http://tomeko.net/software/JSONedit/)

**Comment by alphastar868** [comment]
FYI: Successfully compiled [0c37f17 ](https://github.com/eloaders/I-Nex/commit/0c37f1732cd3a4e6198c8abba2c2622d0b75ca85) using */dists/redhat/i-nex.spec* on **Centos 7.2 (1511)**.

Dependencies are another matter though. Here is a short guide to the steps:

1. Enable [**EPEL repo** from FedoraProject](https://fedoraproject.org/wiki/EPEL), to simplify finding dependency packages
2. Install **Development Tools** for CentOS 
`sudo yum group install "Development Tools"`
3. Setup the [RPM build environment](https://wiki.centos.org/HowTos/SetupRpmBuildEnvironment) under CentOS
4. (Re)build/install **libcpuid11** and **libcpuid-devel** (from and gambas3 from [copr/brollylssj repo](https://copr.fedorainfracloud.org/coprs/brollylssj/libcpuid/).  
5. (Re)build/install **gambas3*** from [Fedora Rawhide repo](https://fedoraproject.org/wiki/Releases/Rawhide). 

**NOTE:** I rebuilt the x86_64.SRPM in CentOS for steps 4 and 5, rather than install the Fedora (fc) RPM from the repo.  Doing so means that you also have to satisfy the dependencies for building these packages as well.  

**To install dependencies required for building I-Nex do:**

```
sudo yum localinstall ~/rpmbuild/RPMS/x86_64/libcpuid*
sudo yum localinstall ~/rpmbuild/RPMS/x86_64/gambas3-{devel,gb-desktop,gb-form,\
gb-gtk,gb-gui,gb-image,gb-qt5,gb-settings,runtime}*

sudo yum install ImageMagick automake autoconf fdupes hicolor-icon-theme net-tools \ 
libX11-devel gtkglext-devel procps-ng procps-ng-devel i2c-tools pciutils pkgconfig xz
```

**Build and install I-Nex packages:**

1. Download the [included SPEC file](https://github.com/eloaders/I-Nex/blob/master/dists/redhat/i-nex.spec)
2. Download the source. [most recent commit](https://github.com/eloaders/I-Nex/archive/<gittag>.zip).  More recent versions include better support for CentOS.
3. Edit the SPEC file to change *%gitdate*,*%gitlong* and *%gittag* to match <commit>
4. Execute the following (replace `<gittag>` and `<gitlong>` with the correct hashes from the download above)

```
cp i-nex.spec ~/rpmbuild/SPECS/
cp <gittag>.zip to I-nex-<gitlong>.zip
rpmbuild -ba ~/rpmbuild/SPECS/i-nex.spec
sudo yum localinstall ~/rpmbuild/{noarch,x86_64}/i-nex*<gittag>*
```
I-Nex is installed to Applications > System Tools in GNOME.  It can also be executed from the Terminal in GNOME for debugging.

**Pull request merged**
